### ISSUE TITLE
[Feat. request] Hide monster health bar

### ISSUE THREAD

**Issue by WetU** [Haato3o/HunterPie-v2#130]
I ask for adding option to hide health bar for monster widget.

I want to only see monster icon, name, crown, and capture icon to be added later.

**Comment by Haato3o** [comment]
That will be possible when I implement the theme support, I don't want to add a toggle for individual components of each widget, that would be too much work

**Comment by WetU** [comment]
Thx for your response.
I expect the theme support feature.
