### ISSUE TITLE
Auto Update not working (current version: 2.2.0.358)

### ISSUE THREAD

**Issue by gixxpunk** [Haato3o/HunterPie-v2#154]
Update starts to download, but after a couple of kb hangs and stops. Need to kill process with task manager.

https://i.imgur.com/KGQOAlx.png
https://i.imgur.com/YkBLdh7.png
https://i.imgur.com/gleTOuS.png

Happens all the time. No idea to fix it, so I just skip the update for now.

**Comment by Haato3o** [comment]
Few reasons why that could happen:

- Your antivirus is deleting it's files, make an exception for HunterPie folder in your antivirus settings
- Your HunterPie is in a folder in your desktop, desktop is considered a special folder and Windows protects it which makes HunterPie not be able to write to files in it's folder. If your HunterPie is in the desktop, move it somewhere else like the documents folder
- Your HunterPie folder is in read-only mode, make sure it is not in read only.

After you check those 3 reasons, if you see a folder called "temp" in your HunterPie folder, delete it and run HunterPie again.

**Comment by Haato3o** [comment]
Closing this as there hasn't been a reply in 2 weeks
