### ISSUE TITLE
Bug: Unable to  capture the widgets with OBS (Stream Mode already ON)

### ISSUE THREAD

**Issue by 1155159410** [Haato3o/HunterPie-v2#167]
Thank you for creating this wonderful mod, I have been using this it v1. :)

## Issue:
I am trying to use OBS with the source of `Game Capture`, to capture MHW and the overlay. `Stream Mode` is turned on for all widgets, and I have tried both with and without administrator, but still, OBS cannot capture the overlay. (As shown in the below capture; sorry that my UI is not in English)
![屏幕截图 2022-08-11 105617](https://user-images.githubusercontent.com/79906737/184060485-dc0e3c49-04a1-4c4e-aff7-8029de2fb805.png)

## Setup Environment:
Windows 11
Latest HunterPie v2
Monster Hunter: World
MHW Screen Mode: Borderless Window

### P.S.
Actually, I am trying to play MHW through Steam Remote Play because of some reason. And the Steam Remote Play is not able to capture the overlay. Then I’m guessing that maybe it is using a similar technic as the OBS Game Capture. So, I gave a try to use OBS to capture the overlay with HunterPie’s `Stream Mode` (although the technic of Steam Remote Play and OBS may not be related). Thus, I found this issue that OBS cannot capture the overlay either.

**Comment by Haato3o** [comment]
Stream Mode isn't implemented yet, not sure when I'll implement it but I don't have plans for it at the moment

**Comment by SamuelGaona** [comment]
Any news on this?

**Comment by Zhicyuyan** [comment]
> Stream Mode 尚未实现，不确定我何时实现它，但我目前没有计划

Is the Stream mod implemented now?
