### ISSUE TITLE
Failure to load address

### ISSUE THREAD

**Issue by WesCook** [Haato3o/HunterPie-v2#178]
I've just downloaded HunterPie v2 for the first time, and am unfortunately receiving an error in the log.

>Failed to load address for Monster Hunter Rise v11.0.2.0

![image](https://user-images.githubusercontent.com/792101/187044726-b9551ab1-dbd1-44b7-a46b-01c9c013ce5b.png)

I've tested with and without REFramework by temporarily renaming dinput8.dll.  I moved the executable away from the desktop as mentioned in the readme.

Any suggestions?  Anything you'd like me to test?  Thank you.

HunterPie v2.3.0.133

**Comment by kinyang007** [comment]
Same issue on my side. Any suggestions?

**Comment by monk233** [comment]
Download the latest Monster Hunter rise.11.0.2.0.map file
![image](https://user-images.githubusercontent.com/52564907/187053504-61840ceb-5228-4352-9cef-abeacc7128f1.png)
Move to the unzipped directory of your local hunterpie V2
![image](https://user-images.githubusercontent.com/52564907/187053570-83ddedfc-dfb1-410c-a9cf-738f38273df4.png)

**Comment by P00t1s** [comment]
> Download the latest Monster Hunter rise.11.0.2.0.map file ![image](https://user-images.githubusercontent.com/52564907/187053504-61840ceb-5228-4352-9cef-abeacc7128f1.png) Move to the unzipped directory of your local hunterpie V2 ![image](https://user-images.githubusercontent.com/52564907/187053570-83ddedfc-dfb1-410c-a9cf-738f38273df4.png)

Just want to drop in and say this fixed the issue for me.

**Comment by WesCook** [comment]
Easy fix.  Thanks @kinyang007!

I'll assume this needs to be pushed in the latest release, so I'll leave this open for the time being as a reminder.

**Comment by stradivari** [comment]
This unfortunately didn't fix the issue for me, and instead leads to the following error:

![20220829_hunterpie_error](https://user-images.githubusercontent.com/1923674/187221152-7adc9bf0-9cd6-4632-9a4d-1c779a276de1.png)

Any suggestions in addressing this would be helpful. Thanks!

**Comment by monk233** [comment]
> 



> This unfortunately didn't fix the issue for me, and instead leads to the following error:
> 
> ![20220829_hunterpie_error](https://user-images.githubusercontent.com/1923674/187221152-7adc9bf0-9cd6-4632-9a4d-1c779a276de1.png)
> 
> Any suggestions in addressing this would be helpful. Thanks!

It looks like an address reading error，Please check your address file
![image](https://user-images.githubusercontent.com/52564907/187243540-12e5f334-6ef2-4472-ac39-af135b75e15e.png)

**Comment by stradivari** [comment]
I checked the file (which I downloaded from this repo) and it seems to be the same as what you linked. What should I be checking/changing?

![hunterpie_map_file_addresses](https://user-images.githubusercontent.com/1923674/187291337-4e8ff1c7-2a5f-4360-9f7d-0567bdee22ce.png)

**Comment by monk233** [comment]
> 

Why is the HTML format different from mine

**Comment by monk233** [comment]
> I checked the file (which I downloaded from this repo) and it seems to be the same as what you linked. What should I be checking/changing?
> 
> ![hunterpie_map_file_addresses](https://user-images.githubusercontent.com/1923674/187291337-4e8ff1c7-2a5f-4360-9f7d-0567bdee22ce.png)

Why is the HTML format different from mine
@stradivari

**Comment by stradivari** [comment]
I have no idea. I downloaded it from the repo and have done nothing else with the file besides open it in Sublime Text.

**Comment by monk233** [comment]
> I have no idea. I downloaded it from the repo and have done nothing else with the file besides open it in Sublime Text.

I tried to open it with Subline text, but there was no HTML format.
I think you downloaded the wrong file.
Copy the contents of this [file](https://github.com/Haato3o/HunterPie-v2/blob/main/HunterPie/Address/MonsterHunterRise.11.0.2.0.map)
Then paste and overwrite it into your local file Monster Hunter rise.11.0.2.0.map
![image](https://user-images.githubusercontent.com/52564907/187355966-0814088a-1407-40ee-bc1e-59db1a693ba2.png)
@stradivari

**Comment by stradivari** [comment]
That addressed my issue. Thank you!

**Comment by Haato3o** [comment]
> Easy fix. Thanks @monk233!
> 
> I'll assume this needs to be pushed in the latest release, so I'll leave this open for the time being as a reminder.

My PC died so I couldn't build HunterPie and publish the latest release.

**Comment by Haato3o** [comment]
Also, should be fixed in v2.3.0.134
