### ISSUE TITLE
Failed to load address from MHR v12.0.0.0

### ISSUE THREAD

**Issue by notEis** [Haato3o/HunterPie-v2#220]
I need a new map file for the new version 12.0.0.0

**Comment by notEis** [comment]
I have found at here.
https://github.com/Haato3o/HunterPie-v2/blob/main/HunterPie/Address/MonsterHunterRise.12.0.0.0.map

**Comment by Haato3o** [comment]
You'll need more than a map file for HunterPie to work in v12, just enable HunterPie auto-update and you're fine.

**Comment by notEis** [comment]
> You'll need more than a map file for HunterPie to work in v12, just enable HunterPie auto-update and you're fine.

I have enabled the auto-update setting, but it throws the **Could not reach any of HunterPie's hosts** Error
![QQ截图20221001145714](https://user-images.githubusercontent.com/59189638/193397183-41fc1b8e-2a7c-477c-a5f4-a7908d87f247.png)
So I cannot update to the latest version.What should I do to resolve it

**Comment by Haato3o** [comment]
Something is blocking your connection to the server, could be Hamachi or firewall, or even the GFW if you live in china.
