### ISSUE TITLE
Question : Is there / will there be a way to change password if we lose it?

### ISSUE THREAD

**Issue by MegaJulien** [Haato3o/HunterPie-v2#243]
Everything is in the title.

I created my account, but it didn't let me connect. After some time, i came back i noticed i didn't wrote the password.

**Comment by Haato3o** [comment]
There will be a "Forgot password" button soon that will let you change your password. As for your issue, if you didn't write a password, then the account didn't get created, accounts need a password with at least 8 characters for an account to be created succesfully

**Comment by MegaJulien** [comment]
I did write a password when i created the account, but i didn't note the password because i was leaving after creating the account. I even verified it, but it didn't let me access the account at that time.

**Comment by Haato3o** [comment]
Oh, I see. I can add the "Forgot password" button today and will let you know here

**Comment by Haato3o** [comment]
Just a little update on this issue: I'm still working on it and it will be probably live by the weekend, but if you want I can manually delete the created account so you can create a new one, just DM me on Discord (Haato#0001)

**Comment by MegaJulien** [comment]
Great. I can wait. Thank you.

**Comment by Haato3o** [comment]
@MegaJulien I added password reset in `v2.4.0.502`
