### ISSUE TITLE
Feat(Core|UI): Damage Widget for Rise

### ISSUE THREAD

**Issue by Haato3o** [Haato3o/HunterPie-v2#32]
- [x] View
- [x] ViewModel
- [x] Source

**Comment by FerLuisxd** [comment]
Not sure if yet implemented! Would love to see this widget to finish! I saw other people that currently have a DPS meter, [1](https://github.com/GreenComfyTea/MHR-Overlay) and [2](https://github.com/coavins/mhrise-coavins-dps). Thought this would help

**Comment by Haato3o** [comment]
> Not sure if yet implemented! Would love to see this widget to finish! I saw other people that currently have a DPS meter, [1](https://github.com/GreenComfyTea/MHR-Overlay) and [2](https://github.com/coavins/mhrise-coavins-dps). Thought this would help

I've finished only the View and ViewModel parts, so basically I have the design and behavior working fine so far, however, getting the data from the game is the real issue here, the only data the game stores directly in the memory is the local player and both buddies general damage (that includes damage dealt to small monsters, environment monsters, other big monsters, etc).
The plugins for REFramework  work by hooking the damage function inside the game, since REFramework runs inside the game's process, it's easy for them to just hook to the game and do whatever they need to, but HunterPie works outside of the game, so hooking stuff isn't possible unless I do one of these: 
1. I write everything in assembly and inject it into the game and make a trampouline from the damage function to my assembly.
2. Inject DLL into the game and open a socket for communication with the "external world".
3. Rely on REFramework to get the data

Right now I'm waiting for Sunbreak release to actually work on it because there's no point in spending a lot of time figuring out the best way to do it just for the game to change everything in 2 ~ 3 months.

**Comment by neyb** [comment]
I believe you should really on re framework because it would be less work to maintain (and probably will be faster to implement) from version to version.

Maybe switch on dll later (feels more stable than assembly injection).

I dislike reframework for few reasons... But it seems to be the best atm.

**Comment by D3SL** [comment]
I've used some reframework based overlay widgets and for some reason for some people they cause a severe performance issue. I've got a Ryzen 5 and 6800XT, so no reason to experience any problems at all, but reframework overlays give me severe hitching and stuttering every other second or so.

**Comment by Shadowex3** [comment]
I've used some reframework based overlay widgets and for some reason for some people they cause a severe performance issue. I've got a powerful enough computer to moot any performance issues in rise, but reframework overlays not only drop me by a substantial amount they also give me severe hitching and stuttering every other second or so.

**Comment by Haato3o** [comment]
> any news before sunbreak ?

I'm not touching Rise until they release Sunbreak, too risky to start new researches now with the risk of stuff changing in memory

**Comment by Haato3o** [comment]
Done in v2.2.0
