### ISSUE TITLE
If possible add a linux version

### ISSUE THREAD

**Issue by osafaimal** [Haato3o/HunterPie-v2#45]
hello,
i've tried to launch hunterPie with proton, it say me install .NET in wine. I've tried with mono and it say the file doesn't contain a valid CIL image.
I don't know what to run it with or how to configure the tool to do so.
 Would it be possible to recompile it for linux or the libraries are really windows specific and complicated to adapt to linux?

**Comment by osafaimal** [comment]
if you have an other solution I'll take it.

**Comment by Haato3o** [comment]
> Would it be possible to recompile it for linux or the libraries are really windows specific and complicated to adapt to linux?

HunterPie works by reading the game process memory, reading memory relies on calling native functions from `kernel32.dll` and that's a Windows library. I did abstract the Memory implementation so I can implement other ways (in this case, implement other native p/Invokes) but I don't know Linux nor Wine so I don't even know if the static addresses and offsets for data in the game are the same between Windows and Linux.

Besides the Memory reading part, there are also other parts of HunterPie that rely on Window's native libraries, though they're not really essential for it to work.
