### ISSUE TITLE
It always prompts me to install .net

### ISSUE THREAD

**Issue by everglowfk** [Haato3o/HunterPie-v2#63]
Hello
I have installed .net(Microsoft Windows desktop runtime-5.0.15), but It still prompt me to download when I open hunterpie. I don't know how to solve it :(
![1](https://user-images.githubusercontent.com/52858048/162269546-1cb34efb-1988-4ed1-b5de-7dae06552373.png)

**Comment by Haato3o** [comment]
Did you run the `Microsoft Windows Desktop Runtime - 5.0.15 (x64)` installer? That popup you're getting when you run HunterPie is from Windows itself, so if it is prompting you that then it either means:

1. You don't have it installed
2. Windows couldn't find the runtime installation

To check if the runtime is properly installed, open your windows command prompt (or powershell) and type `dotnet --list-runtimes` and see if `Microsoft.NETCore.App 5.0.15` appears on the list.

![image](https://user-images.githubusercontent.com/35552782/162327806-4bbe16c3-0848-408b-b67f-937ad5f976d1.png)

**Comment by everglowfk** [comment]
After I saw your reply, I did the following:

1. I downloaded and installed **Microsoft.NETCore. App 5.0.15** ,Hunterpie does not run.

2. Then I installed **Microsoft.NET Runtime 5.0.15**，Hunterpie is working properly.

3. I tried to uninstall **Microsoft NETCore.  App 5.0.15**,Hunterpie still work.

I'm sorry for my poor English, and thank you for your patience and reply.
