### ISSUE TITLE
Wirebug Overlay

### ISSUE THREAD

**Issue by yshtola22** [Haato3o/HunterPie-v2#91]
Seems like it displays all the time? I enabled the setting to hide it. But it doesn't work. Other stuff seems to hide correctly during dialog text. Wirebug symbols are still present. I had to move them off the dialogue window just to be functional.

**Comment by Haato3o** [comment]
It doesn't display all the time, it's just that NPC dialog isn't detected by HunterPie yet. It will be fixed in the next version though :)

**Comment by yshtola22** [comment]
Oh! xD Well thanks!

Any way you can do Action or Item Bar overlays to replace the existing ones? :3 I'd love to put them on the opposing side of the screen.

**Comment by Haato3o** [comment]
> Oh! xD Well thanks!
> 
> Any way you can do Action or Item Bar overlays to replace the existing ones? :3 I'd love to put them on the opposing side of the screen.

Hmm, that might be possible but seems too much work to do at the moment, I'm focused on adding other features first (that were in [legacy](https://github.com/Haato3o/HunterPie) but aren't in v2 yet)

**Comment by Haato3o** [comment]
Fixed in #86
